dname.c
A name has to be at least 1 byte, so return `NULL` if this is not the case.
Before that change, we had a paradoxical situation where `ldns_dname_new(0, NULL)` returned a valid RDF pointer, but trying to use that pointer with functions such as `ldns_rdf_print()` had an undefined behavior.
=> Do not allow empty names in `ldns_dname_new()`

dnssec.c, dnssec_sign.c, host2str.c, keys.c
The bn.h/dsa.h/rsa.h headers aren't included even though APIs from
them are used heavily.  Include them in files that need them.  If
we don't, we might hit build failures depending on how OpenSSL was
configured.
=> include used openssl headers

configure.ac
Modern Linux provides inet_ntop in `-lsocket`. Modern OS X provides inet_ntop in `-lc`. Modern Solaris provides inet_ntop in `-lsocket -lnsl`. Older Solaris provides inet_ntop in `-lresolv`.
Ditto for inet_pton.
Tested OK on Ubuntu 18.04, OS X 10.9, OS X 10.5, and Solaris 11.3.
=> Add additional search libs for inet_ntop and inet_pton

Makefile.in
Needs to be prefixed with "$(srcdir)/", otherwise out of tree build fails.
Signed-off-by: David Oberhollenzer <goliath@infraroot.at>
=> Fix broken reference to packaging/libldns.pc.in

dane.c
dane.c: Use OpenSSL context options
Make ldns aware of OpenSSL's SSL_OP_NO_SSLv2, SSL_OP_NO_SSLv3, SSL_OP_NO_TLSv1, SSL_OP_NO_DTLSv1 and SSL_OP_NO_COMPRESSION. Guard use of the defines in case the OpenSSL library changes them or removes them.
Add ldns_dane_new_ssl_context() to obtain context with SSL_CTX_new. Use NoOpenSSLv2, NoOpenSSLv3 and NoOpenSSLCompression on the context.
=> Use OpenSSL context options

examples/ldns-dane.c
examples/ldns-dane.c: Use OpenSSL context options
Ditto for the example code.
=> Update ldns-dane example to use OpenSSL context options

makedist.sh
The GNU folks recommend updating config.guess and config.sub using Savannah. It is the latest version of the scripts and sidesteps problems on old clients and buggy scripts.
Also see [13.4.6 config.guess, config.sub at top level](https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html) in the manual.
This is safe. I've been doing it for years, even with tarballs built by other people. For example, if I download a release tarball I will overwrite the supplied [config.guess and config.sub](https://github.com/noloader/Build-Scripts/blob/master/fix-config.sh#L69) with the latest from Savannah.
=> Use fresh config.guess and config.sub when building distro

.gitignore
A `git add *` will skip the Emacs backup files.
=> Add Emacs backup files to gitignore

dnssec.c, examples/ldns-dane.c, examples/ldns-keygen.c, examples/ldns-signzone.c, examples/ldns-verify-zone.c, host2str.c, keys.c, ldns/keys.h, rr_functions.c
Signed-off-by: Rosen Penev <rosenp@gmail.com>
This is a more comprehensive fix than the previous.
I could be wrong but I think the build failures can be replicated with -Werror=implicit-function-declaration and -DOPENSSL_API_COMPAT=0x10100000L when deprecated APIs are enabled.
=> Fix compilation without DSA and deprecated APIs

configure.ac, drill/drill.c, examples/ldns-signzone.c, test/60-compile-builddir.tpkg/60-compile-builddir.test
This PR fixes the build failure in 60-compile-builddir. Also see [Issue #79](https://github.com/NLnetLabs/ldns/issues/79).
The essence of the PR is to test for functions like `EVP_cleanup` and `ENGINE_cleanup`. It also adds `--disable-dane-verify`.
I *think* both `--disable-dane-verify` (added with PR) and `--disable-dane-ta-usage` (existing in test) could be tied to `HAVE_SSL` to automatically disable tests when OpenSSL or LibreSSL are not available. However, this PR does not make the change.
This PR should also clear the test failures in [PR #78](https://github.com/NLnetLabs/ldns/pull/78) and [PR #75](https://github.com/NLnetLabs/ldns/pull/75).
=> Fix 60-compile-builddir

.travis.yml
This PR adds additional compilers and platforms for Travis testing.
All of the jobs fail at the moment due to two failures. The first failure is in the UBsan test. The open issue for UBsan is [Issue 71](https://github.com/NLnetLabs/ldns/issues/71). The second failure is in 60-compile-builddir. I can't take credit for the failure. It is being tracked at [Issue 79](https://github.com/NLnetLabs/ldns/issues/79).
=> Add additional compilers and platforms for Travis

configure.ac
This PR fixes one of the Asan test failures.
The Asan test for this PR is:
```
13-unit-tests-base.o: In function `test_base64_encode':
/home/travis/build/noloader/ldns/test/13-unit-tests-base.cYieJC/./13-unit-tests-base.c:26: undefined reference to `rpl_malloc'
13-unit-tests-base.o: In function `test_base64_decode':
/home/travis/build/noloader/ldns/test/13-unit-tests-base.cYieJC/./13-unit-tests-base.c:68: undefined reference to `rpl_malloc'
13-unit-tests-base.o: In function `test_base32_encode':
/home/travis/build/noloader/ldns/test/13-unit-tests-base.cYieJC/./13-unit-tests-base.c:118: undefined reference to `rpl_malloc'
/home/travis/build/noloader/ldns/test/13-unit-tests-base.cYieJC/./13-unit-tests-base.c:118: undefined reference to `rpl_malloc'
```
The other failure - the memory leaks …
=> Fix undefined reference to "rpl_malloc"

test/12-unit-tests-dnssec.tpkg/12-unit-tests-dnssec.c
Asan testing is producing some findings in `12-unit-tests-dnssec.c`. Also see [Travis test results](https://travis-ci.com/NLnetLabs/ldns/jobs/293788254).
```
==5141==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 48 byte(s) in 1 object(s) allocated from:
#0 0x7f913b6fbb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7f913b3cce4a in ldns_rr_new rr.c:27
Indirect leak of 48 byte(s) in 2 object(s) allocated from:
#0 0x7f913b6fbb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7f913b3c5b4d in ldns_rdf_new_frm_data rdata.c:203
Indirect leak of 20 byte(s) in 2 object(s) allocated from:
#0 0x7f913b6fbb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
#1 0x7f913b3c5b61 in ldns_rdf_new_frm_data …
```
=> Fix Asan findings in 12-unit-tests-dnssec.c (GH #84)

util.c
This PR clears a Undefined Behavior in `ldns_serial_arithmitics_time` by using unsigned types for the math. See https://github.com/NLnetLabs/ldns/issues/71 for the finding.
Also see the following from Unbound. A similar issue was cleared with `uint32_t` casts:
* https://github.com/NLnetLabs/unbound/issues/170
* https://github.com/NLnetLabs/unbound/commit/57bbbfc0e6d9
(The failed Travis tests are expected at this point. There are outstanding Asan findings. The sanitizers findings are getting cleared next).
=> Fix UBsan finding in ldns_serial_arithmitics_time (GH #71)

ldns/sha1.h, ldns/sha2.h, sha1.c, sha2.c, test/13-unit-tests-base.tpkg/13-unit-tests-base.c
This PR  accomplishes three things. First, it clears all the pointer-sign warnings in `13-unit-tests-base.c`. Second, it fixes const-ness in `ldns_sha1`, `ldns_sha256` and friends. Third, it fixes system includes so that using `ldns_sha1`, `ldns_sha256` and friends does not result in a compile error on some platforms.
For the third item, Posix includes are used for `uint32_t`, `NULL` and friends. Including `<inttypes.h>` or `<sys/types.h>` is not enough for some platforms. (When testing x86-sha-acceleration I was experiencing compile errors on the BSDs, OS X and Solaris).
This PR does not add additional functionality. It merely clears all the warnings in `13-unit-tests-base.c` and fixes compiles.
If the PR is accepted, I can merge it into x86-sha-acceleration. That has not been done at …
=> Clear errors and warnings for SHA-1 and SHA-256

.travis.yml, Makefile.in, README-Travis.md, configure.ac, contrib/android/15-android.conf, contrib/android/bootstrap_ldns.sh, contrib/android/install_ndk.sh, contrib/android/install_openssl.sh, contrib/android/install_tools.sh, contrib/android/setenv_android.sh, test/60-compile-builddir.tpkg/60-compile-builddir.test
This PR adds Android testing to Travis. Take two...
There were two major campaigns in this PR. First was the obvious Android scripts and Travis tests. The Android gear was placed in `contrib/android/`. The Travis recipes calls the scripts, and eventually builds and installs LDNS.
The second campaign was a little more subtle. It required subtle fixes to `configure.ac`, `Makefile.in` and `60-compile-builddir.test`.
First, the `configure.ac` used the pair `-lssl` and `-lcrypto` for `LIBSSL_LIBS`. The fact of the matter is, anywhere you use `-lssl`, you need `-lcrypto`. They are a matched set because `-lssl` depends upon `-lcrypto`. They cannot be disgorged.
`ENGINE_load_cryptodev` was also removed from `configure.ac`. LDNS does not use it, and the OpenBSD folks are removing it from their …
=> Add Android testing to Travis

.travis.yml
Both `brew update` and the `install` recipe was producing errors.
The `indent` package under Brew is called `findent`.
Also see:
* [OS X image and “Error: Unknown command: bundle”](https://travis-ci.community/t/os-x-image-and-error-unknown-command-bundle/7493/2) (Travis Message Boards)
* [Travis | Installing Dependencies](https://docs.travis-ci.com/user/installing-dependencies/) (Travis docs)
=> Fix Brew update and install

contrib/ios/install_tools.sh
This PR fixes Travis failures due to Homebrew.
Also see [Homebrew fails because an automake update is an error?](https://travis-ci.community/t/homebrew-fails-because-an-automake-update-is-an-error/7831/3) on the Travis Community message boards. According to the Travis folks `brew update` can fail if there are no updates. And `brew install` can fail if there's an update available. The simplest way to cover all the bases is to return `true` under all conditions.
Returning `true` for some conditions is incorrect, like a network error. However, we need to get through `brew update` and `brew install`, which is the common case.
=> Fix Travis failures due to Homebrew

packaging/ldns-config.in
Libraries provided by ldns-config --libs differs from pkg-config --libs
ldns, when python compilation is enabled. It may bring undesired
dependencies to consuming software. Openssh is good example.
Move python libraries to --python-libs, in case it is required. Common
C build do not require python libraries at all.
=> Move python libraries to separate options in ldns-config

Changelog, dnssec_sign.c, dnssec_verify.c, rr.c
The TTL value for any NSEC RR SHOULD be the same TTL value as the lesser of the MINIMUM field of the SOA record and the TTL of the SOA itself. This matches the definition of the TTL for negative responses in [RFC2308].
Edit see: https://datatracker.ietf.org/doc/draft-ietf-dnsop-nsec-ttl/
Implementation status on: https://trac.ietf.org/trac/dnsop/wiki/draft-ietf-dnsop-nsec-ttl
=> draft-ietf-dnsop-nsec-ttl-01 NSEC TTLs with signing

Makefile.in
If ldns is built from a directory which is different from the source directory, the installation will fail as libldns.pc is searched in a wrong path.
This PR fixes the problem.
Reproducer:
```
cd ldns
mkdir build
cd build
../configure
make
make install
```
=> fix ldns.pc installation when building out-of-source

examples/ldns-verify-zone.c
Instead of reporting whatever `result` was set to from earlier.
=> ldns-verify-zone: report ZONEMD errors correctly

Makefile.in, ax_pkg_swig.m4, ax_python_devel.m4, m4/ax_config_feature.m4, m4/ax_have_poll.m4
Python 3.10 prints warning about deprecated distutils. Current autoconf snippet configuring ldns cannot configure with python 3.10.
This would update all m4 files from archive and include also change to use architecture dependent site-arch python path. Because it no longer exports PYTHON_LDFLAGS, PYTHON_LIBS is used instead.
=> Update all m4 files from autoconf-archive project

Makefile.in
When building ldns with slibtool (https://dev.midipix.org/cross/slibtool) it fails.
```
rdlibtool --mode=link clang -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 linktest.lo -lssl -lcrypto -lldns -o linktest
rdlibtool: lconf: {.name="libtool"}.
rdlibtool: fdcwd: {.fdcwd=AT_FDCWD, .realpath="/tmp/ldns"}.
rdlibtool: lconf: fstatat(AT_FDCWD,".",...) = 0 {.st_dev = 34, .st_ino = 38765}.
rdlibtool: lconf: openat(AT_FDCWD,"libtool",O_RDONLY,0) = 3.
rdlibtool: lconf: found "/tmp/ldns/libtool".
rdlibtool: link: clang .libs/linktest.o -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g -O2 -lssl -lcrypto -lldns -o .libs/linktest
/usr/bin/ld: cannot find -lldns
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
rdlibtool: exec …
```
=> Makefile.in: Link with the .la files.

host2wire.c, ldns/host2wire.h
I'm using ldns in a project, but have a need for some specific requests to be generated without domain name compression. Right now there's no easy way to do that as the compression logic in `ldns_pkt2wire` is unconditional. Adding an `ldns_pkt2buffer_wire_compress` function that I can explicitly call with a NULL rbtree seems like the easiest, least invasive way to add this functionality, and fits with the existing API.
What are your thoughts? Is this functionality you'd like to support in ldns, and if so does this approach seem okay?
=> Provide an API to generate wire buffers without compressed domain names

configure.ac, libdns.doxygen.in
Do not require manual changes to libdns.doxygen. Release version got
outdated during recent ldns releases. Configure it with correct version
without extra work needed.
=> Propagate correct version to doxygen template

dnssec.c, host2str.c, keys.c
In the upcoming LibreSSL version 3.5, the DSA and RSA structs will
become opaque, so we should use the OpenSSL 1.1 setters and getters
to fix the build.  The relevant API has been available since
LibreSSL 2.7. The last LibreSSL version (2.6) not having these
accessors was EOL late 2018, so no users should be affected by this
change.
=> Use accessors for DSA and RSA objects

contrib/python/ldns_rdf.i
Triggered by:
ldns.ldns_rdf.new_frm_str("::1", ldns.LDNS_RDF_TYPE_A)
=> Remove undefined status variable from exception

Makefile.in
"distclean" is a *different* kind of target than "destclean"
"destclean" presumably means "uninstall from the destination".
"distclean" means, by convention, "clean the source into the way that
you would like before creating a tarball for distribution"
This switch introduced some ugliness for debian packaging, as can be
seen in
https://salsa.debian.org/dns-team/ldns/-/commit/8b84b73590ac4321e1bf0982d60a7e94b037d6e5
This reverts commit 298b2a65920944aee833d4392e3651f25421c759.
=> Revert "spelling: distclean"

Changelog, contrib/ldnsx/ldnsx.py, contrib/python/docs/source/install.rst, contrib/python/examples/test_dname.py, contrib/python/ldns_resolver.i, contrib/python/ldns_zone.i, dname.c, dnssec_zone.c, doc/API-header.xml, doc/API.xml, doc/CodingStyle, examples/ldns-testns.1, examples/nsd-test/nsd-ldnsd.c, ldns/dane.h, ldns/dnssec.h, ldns/dnssec_sign.h, ldns/dnssec_zone.h, ldns/parse.h, ldns/zone.h, packaging/fedora/ldns.spec, pcat/pcat-diff.c, rdata.c, rr.c, rr_functions.c, zone.c
In #171 i think some attempts at spelling cleanup caused problems.  This series applies more spelling cleanup, and i think it should not cause any problems, but please do review it first :)
If we can get the codebase to a state that a standard spellchecker like "codespell" can run over it with no complaints, then you can build a codespell run into your static analysis to avoid introducing any misspellings.
This series doesn't get it to be fully-clean with codespell 2.1.0-1, but it's much closer.
=> non-substantive: spelling cleanup

rr.c
Fixes #178. Frees line buffer if return code is nonzero.
Question: Fix here or fix in `ldns_fget_token_l_st` to not leave allocated mem if returning nonzero?
=> Free line memory even if zone file parsing fails

host2str.c
Issue #201: endprotoent() needs not to be called until we’re finished with the protoent struct. (Found by running the test suite on OpenBSD.)
=> Fix ldns_rdf2buffer_str_wks not to use after free.

acx_nlnetlabs.m4
Fix -Wstrict-prototypes as it's easy to do and avoids future warnings. Noticed when doing Clang 16 / GCC 14 / C23 work.
For more information, see LWN.net [0] or LLVM's Discourse [1], the Gentoo wiki [2], or the (new) c-std-porting mailing list [3].
[0] https://lwn.net/Articles/913505/
[1] https://discourse.llvm.org/t/configure-script-breakage-with-the-new-werror-implicit-function-declaration/65213 [2] https://wiki.gentoo.org/wiki/Modern_C_porting
[3] hosted at lists.linux.dev.
Signed-off-by: Sam James <sam@gentoo.org>
=> acx_nlnetlabs.m4: fix -Wstrict-prototypes

contrib/ldnsx/ldnsx.py
Imitating the example in the beginning of ldnsx.py results in error:
host:~/rpmbuild# python
Python 3.9.16 (main, Dec  8 2022, 00:00:00)
[GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldnsx
>>> dir(ldnsx)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_rr_types', 'calendar', 'get_rrs', 'isValidIP', 'ldns', 'packet', 'query', 'resolver', 'resource_record', 'secure_query', 'socket', 'sys', 'time', 'warnings']
>>> ldnsx.resolver("9.9.9.9").query("www.hole.fi", "A")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python3.9/site-packages/ldnsx.py", line 220, in __init__
nm_list.reverse() …
=> python3 bindings: ldnsx.py "class resolver" fix

dnssec_sign.c
ldns is one of very few applications relying on being able to pass NULL as last argument to the one-step hashing functions. BoringSSL has removed this functionality in 2017 [1] and LibreSSL 4.0 will do the same. Applications can pass in a correctly-sized buffer on the stack.
[1]: https://boringssl-review.googlesource.com/14528
=> Don't rely on libcrypto returning static buffers

.gitignore, README.snapshots, dane.c, dnssec.c, ldns/parse.h, ldns/radix.h, ldns/rdata.h, lua/rns-specs, pcat/pcat-diff.1
- Update `.gitignore` to ignore more build generated files.
- Fix typos (`the the` -> `the`).
- Fix a memory leak.
- Fix a bad type/potential unsigned integer overflow issue.
=> Address several issues with the ultimate goal being to fix Coverity cited problems

contrib/python/ldns.i
The `ssize_t` type can be int instead of `long`, and the pointer types are incompatible.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
=> 32-bit compatibility for Python SWIG bindings

contrib/python/ldns_rdf.i
The replacement, `SWIG_PyUnicode_AsUTF8AndSize`, has different memory management requirements.
Doesn't `ldns_dname_new_frm_str` make a copy of the input string? Then the `arginit`/`freearg` constructs aren't needed, and the deallocation of the intermediate Python string could happen locally.
=> SWIG_Python_str_AsChar removal in SWIG 4.2.0

contrib/python/ldns_rdf.i
SWIG_Python_str_AsChar needs to be replaced by SWIG_PyUnicode_AsUTF8AndSize. See https://github.com/swig/swig/commit/f89dd59d4b82ece899087682fdb86e94d2611513.
The patch leaves the typemap code unchanged for older versions of SWIG, hence swig-4.2.0 as well as older versions of SWIG can be used.
=> const ldns_rdf * typemap fixes to support swig-4.2.0

keys.c
libressl >= 3.8.1 removed ENGINE support:
> ENGINE support was removed and OPENSSL_NO_ENGINE is set. In spite of this, some stub functions are provided to avoid patching some applications that do not honor OPENSSL_NO_ENGINE.
resulting in the following build failure with gost:
```
./keys.c:167:35: error: 'ENGINE_METHOD_ALL' undeclared (first use in this function)
167 |         if(!ENGINE_set_default(e, ENGINE_METHOD_ALL)) {
|                                   ^~~~~~~~~~~~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/37cc05b78a7004caa1b45d896121f059a4f8ca00
=> keys.c: fix build with libressl >= 3.8.1

edns.c
With -Wstrict-prototypes clang warns that "a function declaration without a prototype is deprecated in all versions of C."
=> Update declaration for function with no arguments

dnssec_zone.c, edns.c, packet.c, rr.c, str2host.c, util.c
This adds an ldns/internal.h C header, containing a copy of the function prototypes for internal functions not exposed in the API.
It effectively works around the following compilation error: error: no previous prototype for function [-Werror,-Wmissing-prototypes]
This header is not installed, and does not affect the API exposed.
Tested on FreeBSD/amd64 (14.0-CURRENT).
Note that this was performed on version 1.8.3, but it seems that it still applies in the same way in the `develop` branch.
=> ldns: fix the build in FreeBSD's base system

examples/ldns-walk.c
Rather than adding \000 to an existing label, add a new label "\000." to the start of the domain name, to find the closes next possible domain name.
This makes ldns-walk not fail on zones where there are more than 2 nsecs between the current label and label+\000.
=> improve 'next-label' algorithm in ldns-walk

examples/ldns-nsec3-hash.c, examples/ldns-signzone.c, keys.c
Extend checks when openssl engine support is missing. Fix build of examples/ldns-nsec3-hash in that case. Clean a bit frm_engine function.
=> Openssl no engine improved support

dnssec.c, test/12-unit-tests-dnssec.tpkg/12-unit-tests-dnssec.c
Initial work copied from https://github.com/NLnetLabs/ldns/pull/187, which was inadvertently closed when its author deleted his GitHub account.
Original PR description:
> Hi, while working on CDS/CDNSKEY in Zonemaster I realized LDNS does not allow calling ldns_calc_keytag() on a CDNSKEY resource record (which is [identical to a DNSKEY resource record](https://www.rfc-editor.org/rfc/rfc7344#section-3.2)).
=> Make ldns_calc_keytag() available for CDNSKEY RR

dnssec.c, test/12-unit-tests-dnssec.tpkg/12-unit-tests-dnssec.c
Hi, similar to #246, this PR proposes to extend `ldns_key_rr2ds()` to support the CDNSKEY resource record.
Depends (based) on #246. You can exclude commit aeaf02e754e25c0d0cba43c9fe67f38d29b0f5c2 for easier reviewing of this PR.
PS: I couldn't find any unitary test for this method in the `test` directory, so this PR is **untested** at the moment. Please feel free to provide additional changes in that regard.
=> Make ldns_key_rr2ds() available for CDNSKEY RR

rr.c
Hi, similar to #246 and #247, this PR proposes to extend `ldns_rr_compare_ds()` and `ldns_rr_compare_ds_dnskey()` to support the CDS and CDNSKEY resource records.
Depends (based) on https://github.com/NLnetLabs/ldns/pull/247.
PS: I couldn't find any unitary test for this method in the test directory, so this PR is untested at the moment. Please feel free to provide additional changes in that regard.
=> Make ldns_rr_compare_{ds,ds_dnskey}() available for CDS and CDNSKEY RRs

drill/securetrace.c
IPv6 DNSSEC trace ("secure trace") does not currently work because only A records are permitted for NSs that are used to trace down from the root. AAAA records are needed for that. Currently an IPv6 DNSSEC trace fails after asking the root, because drill has no valid NSs to continue with.
With this patch, if drill is executed _without_ "-6", the previous behavior continues, with only A records being used.
This is not optimal because without the "-4" or "-6" command line parameters, drill is supposed to randomly use either v4 or v6, as indicated by the `LDNS_RR_TYPE_ANY` default for `qfamily`, but there is no `LDNS_RR_TYPE_A_AND_AAAA`  RR descriptor and I don't know how to join two results of the `ldns_rr_list` data type.
Thanks to Felipe Barbosa for reviewing and input.
=> Make IPv6 DNSSEC tracing work, and revert to previous behaviour otherwise

ldns/rr.h, rr.c
This PR proposes two updates to `ldns_is_rrset()`: 
- to take into account TTL _--> see [RFC2181, Section 5.2](https://www.rfc-editor.org/rfc/rfc2181.html#section-5.2) and [RFC9499, Section 5](https://www.rfc-editor.org/rfc/rfc9499#section-5)_
- do case insensitive comparison of owner names, using function `ldns_dname_compare()` _--> I couldn't find a proper reference from the same RFCs regarding RRsets specifically, but from a practical point on view it seems appropriate. Also see [RFC4343](https://www.rfc-editor.org/rfc/rfc4343)._
PS: I couldn't find any unitary test for this method in the test directory, so this PR is **untested** at the moment. Please feel free to provide additional changes in that regard.
=> Updates to ldns_is_rrset()
